### ISSUE TITLE
[BUG] Expression function replace SQL is not correct position

### ISSUE THREAD

**Issue by ldcuong** [mybatis/thymeleaf-scripting#66]
I using below version:
1. mybatis-thymeleaf v 1.0.2 
2. thymeleaf 3.0.11
3. springboot 2.3.0
4. mybatis 3.5.5 
5. Java 11

When using Expression Function in mybatis thymeleaf.

**Example:**
`SELECT * FROM area 
WHERE 
	NAME LIKE 'Tara%' /*[(${#likes.escapeClause()})]*/ ORDER BY ID
`

**Output result:**
`SELECT * FROM area 
WHERE 
	NAME LIKE 'Tara%' escape '\'
`

**Expected result:**
`SELECT * FROM area 
WHERE 
	NAME LIKE 'Tara%' escape '\' ORDER BY ID
`

ORDER BY ID will be removed, it will be replace all character before comma in same line make sql incorrect.

If we format SQL by line -> SQL will be correct.

**Example:**
```sql
SELECT * FROM area 
WHERE 
	NAME LIKE 'Tara%' /*[(${#likes.escapeClause()})]*/ 
ORDER BY ID
```

**Comment by kazuki43zoo** [comment]
@ldcuong Very sorry for late reply.

This behavior is limitation using this library because use textual template feature(CSS mode) of the Thymeleaf to parse SQL template. As workaround, there are following two solutions. 

### Solution 1 (This solution is your suggestion)
break line after `/*[(${#likes.escapeClause()})]*/`

### Solution 2
Add `/**/` after `/*[(${#likes.escapeClause()})]*/`.

e.g)

```
SELECT * FROM area WHERE NAME LIKE 'Tara%' /*[(${#likes.escapeClause()})]*//**/ ORDER BY ID
```

translated to follows:

```
SELECT * FROM area WHERE NAME LIKE 'Tara%' ESCAPE '\'/**/ ORDER BY ID
```

**Comment by kazuki43zoo** [comment]
We'll add the explanation for this limitation and workaround on reference documentation.
